//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YGNSOCCER.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Floor
    {
        public int F_CD { get; set; }
        public string F_Type { get; set; }
        public Nullable<bool> F_IsDeleted { get; set; }
        public string F_InsertOPTCD { get; set; }
        public Nullable<System.DateTime> F_InsertOPTDateTime { get; set; }
        public string F_UpdateOPTCD { get; set; }
        public Nullable<System.DateTime> F_UpdateOPTDateTime { get; set; }
    }
}
