//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YGNSOCCER.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Offers
    {
        public int O_CD { get; set; }
        public byte[] O_Type { get; set; }
        public Nullable<bool> O_IsDeleted { get; set; }
        public string O_InsertOPT_CD { get; set; }
        public Nullable<System.DateTime> O_InsertOPT_Datetime { get; set; }
        public string O_UpdateOPT_CD { get; set; }
        public Nullable<System.DateTime> O_UpdateOPT_DateTime { get; set; }
    }
}
