//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YGNSOCCER.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Roof
    {
        public int R_CD { get; set; }
        public string R_Type { get; set; }
        public Nullable<bool> R_IsDeleted { get; set; }
        public string R_InsertOPTCD { get; set; }
        public Nullable<System.DateTime> R_InsetOPTDateTime { get; set; }
        public string R_UpdateOPTCD { get; set; }
        public Nullable<System.DateTime> R_UpdateOPTDateTime { get; set; }
    }
}
