//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YGNSOCCER.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_TownShp
    {
        public int T_CD { get; set; }
        public string T_Type { get; set; }
        public Nullable<bool> T_IsDeleted { get; set; }
        public string T_InsertOPTCD { get; set; }
        public Nullable<System.DateTime> T_InsertOPTDateTime { get; set; }
        public string T_UpdateOPTCD { get; set; }
        public Nullable<System.DateTime> T_UpdateOPTDateTime { get; set; }
    }
}
