//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YGNSOCCER.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Transportation
    {
        public int T_CD { get; set; }
        public string T_Type { get; set; }
        public Nullable<bool> T_Isdeleted { get; set; }
        public string T_InsertOPT_CD { get; set; }
        public Nullable<System.DateTime> T_InsertOPT_DateTime { get; set; }
        public string T_UpdateOPT_CD { get; set; }
        public Nullable<System.DateTime> T_UpdateOPT_DateTime { get; set; }
    }
}
