//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YGNSOCCER.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_OPT
    {
        public int OPT_CD { get; set; }
        public string OPT_ID { get; set; }
        public string OPT_Name { get; set; }
        public string OPT_Password { get; set; }
        public Nullable<int> OPT_Level_CD { get; set; }
        public string OPT_Phone { get; set; }
        public byte[] OPT_Photo { get; set; }
        public Nullable<bool> OPT_Owner { get; set; }
        public string OPT_Address { get; set; }
        public string OPT_Comment { get; set; }
        public Nullable<bool> OPT_IsDeleted { get; set; }
        public string OPT_Insert_OPTCD { get; set; }
        public Nullable<System.DateTime> OPT_Insert_OPTDateTime { get; set; }
        public string OPT_Update_OPTCD { get; set; }
        public Nullable<System.DateTime> OPT_Update_OPTDateTime { get; set; }
    }
}
