//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YGNSOCCER.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_Booking
    {
        public int Booking_CD { get; set; }
        public Nullable<int> Booking_STD_CD { get; set; }
        public string Booking_Name { get; set; }
        public Nullable<System.TimeSpan> Booking_Time { get; set; }
        public Nullable<System.DateTime> Booking_Date { get; set; }
        public Nullable<byte> Booking_Flag_CD { get; set; }
        public Nullable<bool> Booking_Isdeleted { get; set; }
        public string Booking_Insert_OPTCD { get; set; }
        public Nullable<System.DateTime> Booking_Insert_OPTDateTime { get; set; }
    }
}
