//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YGNSOCCER.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SOCCERDAYEntities2 : DbContext
    {
        public SOCCERDAYEntities2()
            : base("name=SOCCERDAYEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<M_Floor> M_Floor { get; set; }
        public virtual DbSet<M_TownShp> M_TownShp { get; set; }
        public virtual DbSet<M_Offers> M_Offers { get; set; }
        public virtual DbSet<M_Payment> M_Payment { get; set; }
        public virtual DbSet<M_Roof> M_Roof { get; set; }
        public virtual DbSet<M_Transportation> M_Transportation { get; set; }
        public virtual DbSet<Master_Booking> Master_Booking { get; set; }
        public virtual DbSet<Master_OPT> Master_OPT { get; set; }
        public virtual DbSet<Master_STD> Master_STD { get; set; }
    }
}
